### ISSUE TITLE
Typescript type definitions file?

### ISSUE THREAD

**Issue by Outcue** [kennytilton/matrix#3]
Is there any chance of getting a .d.ts file for Cells.js and Model.js? I have been attempting to make one, but have had little success.

**Comment by Outcue** [comment]
I decided to give porting Cells.js to Typescript. One thing I haven't figured out is the correct way to port methods that take a callback and use the => operator. 

One example:

```
function withoutCDependency(fn) {
    return c=>{ let sd = depender;
        depender = null;
        try {
            return fn(c);
        } finally {
            depender = sd
        }
    };
}
```

I'll keep trying!

**Comment by kennytilton** [comment]
Sorry, just spotted this. Strong typing is a challenge for something like Cells, but as long as there is the option to say "anything" I guess one could pull it off. The whole engine is a generic data handler that worries about who is asking and who should be notified, but never cares about the nature of the data it is handling, except for checking if old and new values are "the same".
